FROM alpine:3.15
EXPOSE 80
RUN apk --no-cache update && \
 apk --no-cache add apache2
ADD php /var/www/localhost/htdocs/
RUN addgroup -S apachegroup &&\
adduser -S apacheuser --ingroup apachegroup
RUN chown -R apacheuser:apachegroup /var/www/localhost/htdocs/
USER apacheuser:apachegroup
CMD ["httpd","-D","FOREGROUND"]